# Generated by Django 5.0.7 on 2024-08-11 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_member_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='member_address',
        ),
        migrations.AddField(
            model_name='member',
            name='member_email',
            field=models.EmailField(default='', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 11, 17, 19, 55, 555504)),
        ),
    ]
