# Generated by Django 5.0.7 on 2024-08-11 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_member_member_avatar_alter_member_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 12, 0, 30, 55, 934792)),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_avatar',
            field=models.CharField(default='istockphoto-2132177453-612x612.jpg', max_length=100),
        ),
    ]
